### ISSUE TITLE
[Documentation] [Installation] pip install new Tedana

### ISSUE THREAD

**Issue by jbteves** [ME-ICA/tedana#140]
When trying to configure tedana, I can't seem to get the newest version on GitHub. When I pip install, it says that I only have version 0.0.1, but the version here is 0.0.4. All dependencies are listed as being present. Additionally, when I pip install, tedana is not added to PATH. I've used both standard python and a miniconda install. There is a working tedana wrapped in AfNI on my machine (RHEL 7 server).
I'm not sure where else to put this as there is no place to e-mail for support on here. 
I may also be just plain doing it wrong.

**Comment by tsalo** [comment]
I think that this is the best place to open an issue like yours.

I'm able to install the most recent version of tedana with pip on my Mac, so I don't think it's a problem on PyPi's end. I'm not exactly an expert on debugging like this, but we can walk through what steps you've taken and try to figure out where things could be going wrong.

When you pip install tedana, are you doing `pip install tedana -U` or `pip install tedana --upgrade` (because you already have tedana installed)?

**Comment by jbteves** [comment]
Ah, I see. I was pip install-ing and it failed because I had one packaged with AfNI. After adding --upgrade it successfully installs the new one. However, how would I go about ensuring the old one is still packaged with AfNI, while allowing myself to have a new tedana install that can also be run in say a miniconda environment?

t2smap fails with error: "cannot import name decomposition"

**Comment by tsalo** [comment]
If you install tedana in an environment, does it still default to that version of tedana outside of the environment? If it does, then I'm not sure how to prevent AfNI and tedana from overriding one another. @emdupre do you have any ideas? 

That's an odd error for t2smap, but at least it's in your path. I know that there is a bug in v0.0.4's t2smap due to the fact that the arguments quiet and debug aren't specified, but importing decomposition should be fine. Would you mind sending the full error message, including original call?

**Comment by jbteves** [comment]
Sure. It appears to be a python 2.7 error, I may have really flubbed this install...
"Traceback (most recent call last):
  File "/usr/bin/t2smap", line 9, in <module>
    load_entry_point('tedana==0.0.4', 'console_scripts', 't2smap')()
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 378, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2566, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2260, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/usr/lib/python2.7/site-packages/tedana/workflows/__init__.py", line 5, in <module>
    from .tedana import tedana_workflow
  File "/usr/lib/python2.7/site-packages/tedana/workflows/tedana.py", line 12, in <module>
    from tedana import (decomposition, model, selection, utils)"

**Comment by jbteves** [comment]
It appears to default that way, but I could be doing it incorrectly. I'm a novice when it comes to setting up multiple Python environments, but I'm a few days in and I can related to this [xkcd](https://xkcd.com/1987/).

**Comment by emdupre** [comment]
Ah, yes, `tedana` isn't py2.7 compatible. @afni-rickr and I were having a discussion a few weeks back about how to sync this with afni_proc.py's python version -- I'm not sure if there's a resolution, yet ! Maybe he would know more.

**Comment by jbteves** [comment]
What's strange is that I've created the tedana environment to run in Python 3.4 via miniconda (since I saw there were 3.5 compatibility issues). So I don't understand why it's trying 2.7. 
Quick and dumb thought: is it possible/reasonable to simply clone this repo into a separate location and build a separate environment to run it? That way I can have both?

**Comment by jbteves** [comment]
Thanks! I'll start giving that a try. I guess I should ask a followup: is it recommended that we use this tedana version or the older one? Is this version relatively stable? Is there some documentation which summarizes the differences?

**Comment by jbteves** [comment]
Great news, I can get the help text with the new conda environment. I think it would be useful to add instructions on how to do this until the AfNI conflict is resolved. I'm happy to write out what I did if you guys like, but I'm not sure how your contribution workflow works for documentation

**Comment by afni-rickr** [comment]
Hi @emdupre.  I believe afni_proc.py and the related python programs should work with newer python, and will test again (maybe with 3.6).  There are many AFNI python programs that will not work with python 3, but hopefully at least an afni_proc.py workflow will, if that is sufficient.  If it is not, @jbteves, please let us know what you run into.  I am testing the standard class example now...

**Comment by afni-rickr** [comment]
Okay, running a normal (ted-less) afni_proc.py analysis is still working with 3.6.  We still have not set up tedana_wrapper.py to handle your tedana @emdupre, sorry!  That is now at the top of the (733 line) todo list.  :)  Hopefully we will get it done soon after this 10/22 bootcamp week.  @jbteves, are you hoping to be able to run tedana via afni_proc.py?

**Comment by emdupre** [comment]
You're amazing, @afni-rickr ! :Tada:

So excited to hear that afni_proc.py works with py3, and I'm looking forward to having `tedana` support ! When you have time, we can chat in another issue or on gitter about how I can help make that happen.

**Comment by afni-rickr** [comment]
Thanks @emdupre, that would be great!  Slowly recalling and pondering here, it will be a little more work than I was initially thinking.  Basically, the work cannot be completely hidden in the wrapper code, so afni_proc.py will have to be updated as well.  Maybe that means it would be better to just skip the wrapper in the first place.  While that is less modular, it is more forward thinking, as we hope to use yours alone anyway.  Hopefully I will be pestering you about this in a few weeks, thanks!  :)

**Comment by jbteves** [comment]
Hi @afni-rickr, yes, I'm ultimately hoping to do that. However, I think some users in my case would also like access to the old version as well so they can retain workflows. 
@emdupre and @tsalo please let me know if you'd like me to update documentation on setting up this type of environment, and if so your preferred workflow.

**Comment by emdupre** [comment]
Thanks so much, @jbteves ! Yes, if you're planning to use `tedana` with AFNI it'd be great to add in your experience on how `tedana` interacts with other pipelines. I actually have a pull request open right now to add in some of that -- see https://github.com/ME-ICA/tedana/pull/134. Maybe you could open a pull request to that pull request ? Let me know if you need any pointers in doing so !

Just to note, we're in the midst of a bit of re-calibration -- see #131. I'm hoping that we'll have a meeting with the main developers in the next week or two and will then be able to pick up steam again. All this to say, it'd be great to get your input, but I don't want you to be concerned if it's not merged in right away !

**Comment by jbteves** [comment]
Thanks @afni-rickr 
@emdupre, I'm not actually sure how to do pull requests with documentation at all, nor am I sure if I'm allowed to since I'm not a "member" of me-ica.

**Comment by emdupre** [comment]
Hi @jbteves -- glad to hear you were able to find the info you needed to open the PR !

Were the [Contributing guidelines](https://github.com/ME-ICA/tedana/blob/master/CONTRIBUTING.md) helpful ? If not, let me know what we could do to improve them !
