### ISSUE TITLE
PCA on wavelet-transformed data is failing

### ISSUE THREAD

**Issue by tsalo** [ME-ICA/tedana#170]
Performing PCA on the wavelet-transformed data (i.e., using the `wvpca` flag) is currently raising an error. It's possible that the shape checks I added for the inputs to various functions are too strict, in which case we will need to adjust those and improve the parameter documentation for affect functions.

Given that wvpca is untested and appears to be almost completely unused, I'm marking this as `low-priority`.

Here is the command used:

```shell
dset_dir=/Users/tsalo/Documents/tsalo/tedana-comparison/sandbox/e5_data

tedana -d ${dset_dir}/sub-01_ses-09_task-flashingcheckerboard_run-01_echo-1_desc-preproc_bold.nii.gz \
  ${dset_dir}/sub-01_ses-09_task-flashingcheckerboard_run-01_echo-2_desc-preproc_bold.nii.gz \
  ${dset_dir}/sub-01_ses-09_task-flashingcheckerboard_run-01_echo-3_desc-preproc_bold.nii.gz \
  ${dset_dir}/sub-01_ses-09_task-flashingcheckerboard_run-01_echo-4_desc-preproc_bold.nii.gz \
  ${dset_dir}/sub-01_ses-09_task-flashingcheckerboard_run-01_echo-5_desc-preproc_bold.nii.gz \
  -e 15.4 29.7 44.0 58.3 72.6 --wvpca --debug \
  --out-dir /Users/tsalo/Documents/tsalo/tedana-comparison/sandbox/current-wvpca
```

And the full traceback:

```
INFO:tedana.workflows.tedana:Using output directory: /Users/tsalo/Documents/tsalo/tedana-comparison/sandbox/current-wvpca
INFO:tedana.workflows.tedana:Loading input data: ['/Users/tsalo/Documents/tsalo/tedana-comparison/sandbox/e5_data/sub-01_ses-09_task-flashingcheckerboard_run-01_echo-1_desc-preproc_bold.nii.gz', '/Users/tsalo/Documents/tsalo/tedana-comparison/sandbox/e5_data/sub-01_ses-09_task-flashingcheckerboard_run-01_echo-2_desc-preproc_bold.nii.gz', '/Users/tsalo/Documents/tsalo/tedana-comparison/sandbox/e5_data/sub-01_ses-09_task-flashingcheckerboard_run-01_echo-3_desc-preproc_bold.nii.gz', '/Users/tsalo/Documents/tsalo/tedana-comparison/sandbox/e5_data/sub-01_ses-09_task-flashingcheckerboard_run-01_echo-4_desc-preproc_bold.nii.gz', '/Users/tsalo/Documents/tsalo/tedana-comparison/sandbox/e5_data/sub-01_ses-09_task-flashingcheckerboard_run-01_echo-5_desc-preproc_bold.nii.gz']
DEBUG:tedana.workflows.tedana:Resulting data shape: (59696, 5, 160)
INFO:tedana.workflows.tedana:Computing adaptive mask
DEBUG:tedana.workflows.tedana:Retaining 24786/59696 samples
INFO:tedana.workflows.tedana:Computing T2* map
/Users/tsalo/anaconda/envs/python3/lib/python3.6/site-packages/scipy/stats/stats.py:1706: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  return np.add.reduce(sorted[indexer] * weights, axis=axis) / sumval
DEBUG:tedana.workflows.tedana:Setting cap on T2* map at 1158.56472
INFO:tedana.combine:Optimally combining data with voxel-wise T2 estimates
INFO:tedana.decomposition.eigendecomp:Computing PCA of optimally combined multi-echo data
DEBUG:tedana.decomposition._utils:Creating eimask for echo 0
DEBUG:tedana.decomposition._utils:Eimask threshold boundaries: 22.015 110074.029
INFO:tedana.decomposition.eigendecomp:Making initial component selection guess from PCA results
Traceback (most recent call last):
  File "/Users/tsalo/anaconda/envs/python3/bin/tedana", line 11, in <module>
    load_entry_point('tedana', 'console_scripts', 'tedana')()
  File "/Users/tsalo/Documents/tsalo/tedana/tedana/workflows/tedana.py", line 384, in _main
    tedana_workflow(**vars(options))
  File "/Users/tsalo/Documents/tsalo/tedana/tedana/workflows/tedana.py", line 321, in tedana_workflow
    ste=ste, wvpca=wvpca)
  File "/Users/tsalo/Documents/tsalo/tedana/tedana/decomposition/eigendecomp.py", line 208, in tedpca
    mmixN=vTmixN, full_sel=False)
  File "/Users/tsalo/Documents/tsalo/tedana/tedana/model/fit.py", line 80, in fitmodels_direct
    'mmix ({1})'.format(catd.shape[2], mmix.shape[0]))
ValueError: Third dimension (number of volumes) of catd (160) does not match first dimension of mmix (162)
```

**Comment by tsalo** [comment]
I spent some time figuring out what was going on, and I think the issue is that we just need to wavelet-transform the concatenated data so that we're calculating fit metrics for component time series on echo-specific data with the same dimensions. However, I also noticed that the independence/dependence of the components does not seem to translate over to wavelet-transformed data, because (as you can see in the attached file), the Rho values are enormous. MLE also selects 161 components (out of 160 volumes), because the wavelet transform adds two points in the "time" (but now wavelet) dimension. Honestly, I think we should just cut our losses and remove the wvpca option.

[comp_table_pca.txt](https://github.com/ME-ICA/tedana/files/2856652/comp_table_pca.txt)

**Comment by emdupre** [comment]
Is this removed now, @tsalo ? Should we close this ?

**Comment by tsalo** [comment]
No, wvpca is still implemented.

**Comment by emdupre** [comment]
Do you still want to remove it, though ?

**Comment by tsalo** [comment]
Absolutely, assuming it's not something anyone feels a strong need for.
