### ISSUE TITLE
`getelbow` raises uninformative exception when supplied with an empty array

### ISSUE THREAD

**Issue by tsalo** [ME-ICA/tedana#752]
### Summary
`tedana.selection._utils.getelbow()` and `getelbow_cons()` are functions to identify elbows in one-dimensional arrays (like you would look for in a scree plot). They are used in multiple places in the component selection decision tree. However, in each of those cases, one or more of the arrays being supplied to these functions may be empty, in which case the functions will return something like the following traceback:

```
Traceback (most recent call last):
  File "/opt/anaconda3/bin/tedana", line 33, in <module>
    sys.exit(load_entry_point('tedana', 'console_scripts', 'tedana')())
  File "/Users/handwerkerd/code/tedana_community/master/tedana/tedana/workflows/tedana.py", line 805, in _main
    tedana_workflow(**kwargs)
  File "/Users/handwerkerd/code/tedana_community/master/tedana/tedana/workflows/tedana.py", line 586, in tedana_workflow
    comptable, metric_metadata = selection.kundu_selection_v2(
  File "/Users/handwerkerd/code/tedana_community/master/tedana/tedana/selection/tedica.py", line 250, in kundu_selection_v2
    kappa_elbow = np.min((getelbow(kappas_nonsig, return_val=True),
  File "/Users/handwerkerd/code/tedana_community/master/tedana/tedana/selection/_utils.py", line 85, in getelbow
    p = coords - coords[:, 0].reshape(2, 1)
IndexError: index 0 is out of bounds for axis 1 with size 0
```

I think there are a few places where we can improve how these arrays are handled:

1. Within the `getelbow` functions, we should raise a more informative Exception (or a warning) when an empty array is provided.
2. The functions could return a NaN when an empty array is provided.
3. In cases where multiple calls to the function are combined (see below), we could use the NaN-robust equivalent (e.g., `numpy.nanmean` instead of `numpy.mean`).
    https://github.com/ME-ICA/tedana/blob/d449925378c54c51e7dce55769372f6b2a6242b3/tedana/selection/tedica.py#L250-L251
4. We should review and identify any cases in the decision trees where the functions _might_ fail. That means any time the functions are run on an array that might be empty. There are some places where that's possible and some where it's not.

### Additional Detail
This has come up as a sort of random error in multiple issues: #181, #297, #370, and https://github.com/ME-ICA/tedana/pull/736#issuecomment-878605551, although it does seem to be fairly rare and unpredictable.

### Next Steps
1. Decide whether a more informative exception or returning NaN is preferable.

**Comment by tsalo** [comment]
The plan for this release is to raise an informative error, preferably mentioning the random seed if that does typically fix the problem. We can then work on a more useful fix for the next release.

**Comment by tsalo** [comment]
I just tested our changing the seed on @dowdlelt's (unprocessed) 8-echo dataset (see below), which fails with `getelbow` with the default seed. I tested out 42 (default), 43, 44, and 45. All of them converge in the first ICA, so it's not that they're restarting and ending up with the same seed.

What's funny is that the error happens when trying to calculate an elbow from the non-significant Kappa values, which I assume must be more significant than the standard analysis based on the large number of echoes. In fact, I'd say that that step doesn't scale well with increasing numbers of echoes generally. Worth thinking about.

I'm worried that there is no good advice if the error happens across random seeds, so maybe we need to actually fix this issue now.

```python
tedana -d \
    /Users/taylor/Documents/datasets/logans-dset/sub-pilot/func/sub-pilot_task-rest_run-2_echo-1_bold.nii.gz \
    /Users/taylor/Documents/datasets/logans-dset/sub-pilot/func/sub-pilot_task-rest_run-2_echo-2_bold.nii.gz \
    /Users/taylor/Documents/datasets/logans-dset/sub-pilot/func/sub-pilot_task-rest_run-2_echo-3_bold.nii.gz \
    /Users/taylor/Documents/datasets/logans-dset/sub-pilot/func/sub-pilot_task-rest_run-2_echo-4_bold.nii.gz \
    /Users/taylor/Documents/datasets/logans-dset/sub-pilot/func/sub-pilot_task-rest_run-2_echo-5_bold.nii.gz \
    /Users/taylor/Documents/datasets/logans-dset/sub-pilot/func/sub-pilot_task-rest_run-2_echo-6_bold.nii.gz \
    /Users/taylor/Documents/datasets/logans-dset/sub-pilot/func/sub-pilot_task-rest_run-2_echo-7_bold.nii.gz \
    /Users/taylor/Documents/datasets/logans-dset/sub-pilot/func/sub-pilot_task-rest_run-2_echo-8_bold.nii.gz \
    -e 9.58 21.95 34.32 46.69 59.06 71.43 83.8 96.17 \
    --tedpca mdl \
    --seed 45 \
    --out-dir /Users/taylor/Documents/datasets/tmp/
```
